# .github/workflows/rust-check.yml
name: Rust Code Quality Checks

# Defines workflow triggers.
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Defines the jobs to be executed.
jobs:
  # Defines a job for standard quality checks.
  quality_checks:
    # Specifies the runner environment.
    runs-on: ubuntu-latest
    # Defines the steps for this job.
    steps:
      # Checks out the repository's source code.
      - name: Checkout repository
        uses: actions/checkout@v4
      # Installs the Rust toolchain.
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      # Checks code formatting.
      - name: Check formatting
        run: cargo fmt --check
      # Runs static analysis lints.
      - name: Run Clippy
        run: cargo clippy -- -D warnings
      # Runs unit and integration tests.
      - name: Run tests
        run: cargo test
